### ISSUE TITLE
Error at linking in Kernel:

### ISSUE THREAD

**Issue by Eliminater74** [dragon-tc-tmp/lld#1]
I build my kernel with your Clang, have always done so, and normally everything always goes well.
I even have the correct code to link with CLANG and not gcc..........

But today when I updated with your latest source, I now get this error at link time:

> + ld.lld -EL -O2 --lto-O3 -r -o vmlinux.o --whole-archive built-in.o --no-whole-archive --start-group arch/arm64/lib/lib.a lib/lib.a --end-group
ld.lld: error: built-in.o(init/main.o): Unknown attribute kind (60) (Producer: 'LLVM9.0.0svn' Reader: 'LLVM 8.0.0')

Any ideas what I can do? but when I use the previous build from before, it works great...
This only happens when I use the latest source.............

**Comment by mydongistiny** [comment]
When you build do you set HOSTCC as DragonTC or do you leave it as the default? Like I set these as well when not building inline.

HOSTCC="ccache /media/otherhd/benzorom/prebuilts/clang/host/linux-x86/9.0/bin/clang"
AR="/media/otherhd/benzorom/prebuilts/clang/host/linux-x86/9.0/bin/llvm-ar"

Just asking because the second part of the error has the system clang as the reader. I've only got that error before when compiling assembly files using an older clang with incompatible flags.

**Comment by Eliminater74** [comment]
Um Wow, you kinda lost me on that one.. I would have to say that I leave everything default.
I think I have always left it as default. Should I change it? and you mean change it in Makefile of kernel right? and whats the AR= for? that is a new one too me. Sorry, I am not a pro at all this.. Clang is still something  very new to me, as GCC I have always been around.......

But yeah, I leave it default, but if I should change it let me know what I need to change and change to what. and I will try that out..  

And thanks for the quick response... I knew if anyone knew it would be you..


My Build Script: https://gitlab.com/devoneplus/android-linux-stable-op6t_20190315/blob/oneplus/SDM845_P_9.0-Nebula_20190411/build-anykernel.sh

Other Part to Build Script: https://gitlab.com/devoneplus/android-linux-stable-op6t_20190315/blob/oneplus/SDM845_P_9.0-Nebula_20190411/build-anykernel.cfg

**Comment by mydongistiny** [comment]
llvm-ar makes archives of bitcode to be linked. Try these changes to see if it helps you.

In build-anykernel.cfg make the Clang section at the bottom look like:

```
### --- For CLANG Builds --- ###
CLANG_BUILDS=1
HOSTCC=${TOOLCHAIN_DIR}/clang/${CLANG_NAME}/bin/clang
AR=${TOOLCHAIN_DIR}/clang/${CLANG_NAME}/bin/llvm-ar
CC=${TOOLCHAIN_DIR}/clang/${CLANG_NAME}/bin/clang
CLANG_TRIPLE="aarch64-linux-gnu-"
CLANG_TRIPLE_ARM32="arm-linux-gnueabi-"
```


Then in build-anykernel.sh after line 116 add:

`export HOSTCC=$HOSTCC`
`export AR=$AR`

and after line 668 add:

`		HOSTCC=$HOSTCC AR=$AR \
`

Sorry it took awhile to get back to you, I was at work.

**Comment by Eliminater74** [comment]
> llvm-ar makes archives of bitcode to be linked. Try these changes to see if it helps you.
> 
> In build-anykernel.cfg make the Clang section at the bottom look like:
> 
> ```
> ### --- For CLANG Builds --- ###
> CLANG_BUILDS=1
> HOSTCC=${TOOLCHAIN_DIR}/clang/${CLANG_NAME}/bin/clang
> AR=${TOOLCHAIN_DIR}/clang/${CLANG_NAME}/bin/llvm-ar
> CC=${TOOLCHAIN_DIR}/clang/${CLANG_NAME}/bin/clang
> CLANG_TRIPLE="aarch64-linux-gnu-"
> CLANG_TRIPLE_ARM32="arm-linux-gnueabi-"
> ```
> Then in build-anykernel.sh after line 116 add:
> 
> `export HOSTCC=$HOSTCC`
> `export AR=$AR`
> 
> and after line 668 add:
> 
> `	HOSTCC=$HOSTCC AR=$AR \ `
> 
> Sorry it took awhile to get back to you, I was at work.

ok, I will give this a try and get back with you on that.. Thanks so much for the help.......

Also, you mentioned to me what Host clang you build on Arch, you gave me a link,
I tried building that.. and I get Theme Errors:
about unknown Template, pretty much ,template not found...........

which has to do with Sphinx im sure of.. I  have all that installed.. but still error.....
and its using python2 while most others are using python 3.7..

anyhow, ill let you know how the about works out..

**Comment by mydongistiny** [comment]
I tried building that PKGBUILD last night and it's outdated now. I updated it, you can grab it here:  
https://github.com/mydongistiny/llvm-svn_arch

Not sure about the errors without seeing them, but give it a try.

**Comment by Eliminater74** [comment]
> I tried building that PKGBUILD last night and it's outdated now. I updated it, you can grab it here:
> https://github.com/mydongistiny/llvm-svn_arch
> 
> Not sure about the errors without seeing them, but give it a try.

`[ 25%] Built target docs-clang-man
[ 25%] Building CXX object projects/compiler-rt/lib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/FuzzerSHA1.cpp.o

Theme error:
An error happened in rendering the page index.
Reason: TemplateNotFound()
make[2]: *** [tools/lld/docs/CMakeFiles/docs-lld-html.dir/build.make:58: tools/lld/docs/CMakeFiles/docs-lld-html] Error 2
make[1]: *** [CMakeFiles/Makefile2:100300: tools/lld/docs/CMakeFiles/docs-lld-html.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] Building CXX object projects/compiler-rt/lib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/FuzzerTracePC.cpp.o
[ 25%] Building CXX object projects/compiler-rt/lib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/FuzzerUtil.cpp.o
In file included from /home/eliminater74/Android/toolchains/LLVM-ARCH/llvm-svn_arch/src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMutate.h:15,
                 from /home/eliminater74/Android/toolchains/LLVM-ARCH/llvm-svn_arch/src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMutate.cpp:14:
In member function 'void fuzzer::FixedWord<kMaxSizeT>::Set(const uint8_t*, uint8_t) [with long unsigned int kMaxSizeT = 64]',
    inlined from 'const Word& fuzzer::MemMemTable<kSizeT>::Get(size_t) [with long unsigned int kSizeT = 1024]' at /home/eliminater74/Android/toolchains/LLVM-ARCH/llvm-svn_arch/src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerTracePC.h:65:18,
    inlined from 'size_t fuzzer::MutationDispatcher::Mutate_AddWordFromTORC(uint8_t*, size_t, size_t)' at /home/eliminater74/Android/toolchains/LLVM-ARCH/llvm-svn_arch/src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMutate.cpp:262:37:
/home/eliminater74/Android/toolchains/LLVM-ARCH/llvm-svn_arch/src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDictionary.h:30:11: warning: argument 2 null where non-null expected [-Wnonnull]
     memcpy(Data, B, S);
     ~~~~~~^~~~~~~~~~~~
In file included from /usr/include/c++/8.2.1/cstring:42,
                 from /home/eliminater74/Android/toolchains/LLVM-ARCH/llvm-svn_arch/src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDefs.h:17,
                 from /home/eliminater74/Android/toolchains/LLVM-ARCH/llvm-svn_arch/src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMutate.cpp:11:
/usr/include/string.h: In member function 'size_t fuzzer::MutationDispatcher::Mutate_AddWordFromTORC(uint8_t*, size_t, size_t)':
/usr/include/string.h:42:14: note: in a call to function 'void* memcpy(void*, const void*, size_t)' declared here
 extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
              ^~~~~~
[ 25%] Building CXX object projects/compiler-rt/lib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/FuzzerUtilDarwin.cpp.o
/usr/lib/python3.7/site-packages/recommonmark/parser.py:63: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
[ 25%] Building CXX object projects/compiler-rt/lib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/FuzzerUtilFuchsia.cpp.o
[ 25%] Building CXX object projects/compiler-rt/lib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/FuzzerUtilLinux.cpp.o
[ 25%] Building CXX object projects/compiler-rt/lib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/FuzzerUtilPosix.cpp.o
[ 25%] Building CXX object projects/compiler-rt/lib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/FuzzerUtilWindows.cpp.o
[ 25%] Built target RTfuzzer.x86_64
[ 25%] Built target docs-clang-html
[ 25%] Built target docs-dsymutil-man
make: *** [Makefile:152: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
`

This is the error I get, I know its related to sphinx..

**Comment by Eliminater74** [comment]
> llvm-ar makes archives of bitcode to be linked. Try these changes to see if it helps you.
> 
> In build-anykernel.cfg make the Clang section at the bottom look like:
> 
> ```
> ### --- For CLANG Builds --- ###
> CLANG_BUILDS=1
> HOSTCC=${TOOLCHAIN_DIR}/clang/${CLANG_NAME}/bin/clang
> AR=${TOOLCHAIN_DIR}/clang/${CLANG_NAME}/bin/llvm-ar
> CC=${TOOLCHAIN_DIR}/clang/${CLANG_NAME}/bin/clang
> CLANG_TRIPLE="aarch64-linux-gnu-"
> CLANG_TRIPLE_ARM32="arm-linux-gnueabi-"
> ```
> Then in build-anykernel.sh after line 116 add:
> 
> `export HOSTCC=$HOSTCC`
> `export AR=$AR`
> 
> and after line 668 add:
> 
> `	HOSTCC=$HOSTCC AR=$AR \ `
> 
> Sorry it took awhile to get back to you, I was at work.

I still get this error, after applying your changes:

> ++ modversions
++ '[' -z y ']'
++ '[' -z '' ']'
++ return
+ ld.lld -EL -O2 --lto-O3 -r -o vmlinux.o --whole-archive built-in.o --no-whole-archive --start-group arch/arm64/lib/lib.a lib/lib.a --end-group
ld.lld: error: built-in.o(init/main.o): Unknown attribute kind (60) (Producer: 'LLVM9.0.0svn' Reader: 'LLVM 8.0.0')
+ on_exit
+ '[' 1 -ne 0 ']'
+ cleanup

The changes: https://gitlab.com/devoneplus/android-linux-stable-op6t_20190315/commit/d6ec0ee4b990a588216ede79f4ffb619b2b42cf5



PS: ill be out for a few days.. but ill check back on friday..

**Comment by Eliminater74** [comment]
Now building the SVN package that you told me about and fixed up. after turning SPHINX off,

I get this error when building the kernel with my known working DTC Clang,

> ld.lld: error: undefined symbol: bcmp
>>> referenced by win_minmax.c
>>>               vmlinux.o:(proc_cmdline_init)

ld.lld: error: undefined symbol: bcmp
>>> referenced by win_minmax.c
>>>               vmlinux.o:(init_device_info)

ld.lld: error: undefined symbol: bcmp
>>> referenced by win_minmax.c
>>>               vmlinux.o:(init_device_info)

ld.lld: error: undefined symbol: bcmp
>>> referenced by win_minmax.c
>>>               vmlinux.o:(init_device_info)

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)

**Comment by mydongistiny** [comment]
Sorry for the late reply, for some reason I'm not getting notified. You need this: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/commit/?h=linux-4.9.y&id=7eceaf5bbfc0ecc0efc89b1f7318e44ea87391cc

**Comment by mydongistiny** [comment]
Also, if can reach me on Hangouts if you have more problems or questions.

**Comment by Eliminater74** [comment]
I sent you a request on hangouts a few days ago..

**Comment by mydongistiny** [comment]
I haven't got any notifications for it. I even checked my spam. It's the same e-mail address as the 'Signed-off by' in my git commits.

**Comment by Eliminater74** [comment]
> I haven't got any notifications for it. I even checked my spam. It's the same e-mail address as the 'Signed-off by' in my git commits.

that is what I used, but it just keeps saying invite pending.. you can add me, its eliminater74@gmail.com and plz just delete this part when you get it.. not that im worried.. but just when you can..
